package sbnz.integracija;

import com.ftn.uns.ac.rs.theperfectmeal.model.Restaurant;

import java.time.LocalDate;
import java.lang.Math;

global Restaurant foundRestaurant;

declare FoundRestaurant
end

rule "Restaurant Compatibility"
	agenda-group "calculating-restaurant-score"
	salience ( $cousine + $pet+$distance +  $prices + $disabled + $alc + $liveMusic + $genre + $hall + $wifi + $parking + $smoking + $playground + $grade + $bonus + $penal )
	when
		RestaurantCompatibility( $rest: restId)
	    CousineScore(restId == $rest, $cousine: cousineScore)
		PlaygroundScore(restId == $rest, $playground: playgroundScore)
		SmokingScore(restId == $rest, $smoking: smokingScore)
		ParkingScore(restId == $rest, $parking: parkingScore)
		WifiScore(restId == $rest, $wifi: wifiScore)
		BusinessHallScore(restId == $rest, $hall: hallScore)
		MusicGenreScore(restId == $rest, $genre: genreScore)
		LiveMusicScore(restId == $rest, $liveMusic: liveMusicScore)
		DisabledScore(restId == $rest, $disabled: disabledScore)
		PricesScore(restId == $rest, $prices: pricesScore)
		PetFriendlyScore(restId == $rest,$pet: petScore)
	    AlcoholScore(restId == $rest, $alc: alcScore)
	    MonthlyBonusScore(restId == $rest, $bonus: bonusScore)
	    MonthlyPenalScore(restId == $rest, $penal: penalScore)
	    GradeScore(restId == $rest, $grade: gradeScore)
	    DistanceScore(restId == $rest, $distance: score)
		$foundRestaurant: Restaurant(id == $rest)
		not FoundRestaurant()
	then
		System.out.println("Restaurant with id " + $rest + " has been choosen.");
		System.out.println("Final Score: " +  ($distance + $cousine + $pet + $prices + $disabled + $alc + $liveMusic + $genre + $hall + $wifi + $parking + $smoking + $playground + $grade + $bonus + $penal  )); 
		drools.getKnowledgeRuntime().setGlobal("foundRestaurant", $foundRestaurant);
		insert(new FoundRestaurant());
end;