package sbnz.integracija;

import com.ftn.uns.ac.rs.theperfectmeal.dto.RecipeRequirements;
import com.ftn.uns.ac.rs.theperfectmeal.model.Recipe;
import com.ftn.uns.ac.rs.theperfectmeal.dto.RecipeCalcInfo;
import com.ftn.uns.ac.rs.theperfectmeal.util.CaloricType;

import java.util.List;


rule "Caloric category - HIGH_CAL"
	agenda-group "ingredients"
	salience 1
    when
        $req: RecipeRequirements(lowCalorie == true)
        $re: Recipe($id: recipeId, $recIng: ingredients)
        $reCalc: RecipeCalcInfo($idCalc: recipeId, $idCalc == $id)
        Number(intValue > 400) from accumulate(
        	RecipeIngredient($t:this, $recIngId: ingredient.getIngredientId(),$calVal: ingredient.getCaloricValue(),$amount: amount) from $recIng,
        	init(double cals = 0;),
        	action(cals = cals + (($calVal * $amount)/100);),
        	reverse(cals = cals - (($calVal * $amount)/100);),
        	result(cals)
        )
    then
    	System.out.println("RECIPE CALORIC CATEGORY RULE FIRED: Recipe "+$re.getRecipeName()+" is HIGH_CAL category.");
    	modify($reCalc){setCaloricType(CaloricType.HIGH_CAL);};
end

rule "Caloric category - LOW_CAL"
	agenda-group "ingredients"
	salience 1
    when
        $req: RecipeRequirements(lowCalorie == true)
        $re: Recipe($id: recipeId, $recIng: ingredients)
        $reCalc: RecipeCalcInfo($idCalc: recipeId, $idCalc == $id)
        Number(intValue <= 400) from accumulate(
        	RecipeIngredient($t:this, $recIngId: ingredient.getIngredientId(),$calVal: ingredient.getCaloricValue(),$amount: amount) from $recIng,
        	init(double cals = 0;),
        	action(cals = cals + (($calVal * $amount)/100);),
        	reverse(cals = cals - (($calVal * $amount)/100);),
        	result(cals)
        )
    then
    	System.out.println("RECIPE CALORIC CATEGORY RULE FIRED: Recipe "+$re.getRecipeName()+" is LOW_CAL category.");
    	modify($reCalc){setCaloricType(CaloricType.LOW_CAL);};
end


