package sbnz.integracija;

import com.ftn.uns.ac.rs.theperfectmeal.dto.RestaurantRequirements;
import com.ftn.uns.ac.rs.theperfectmeal.dto.RestaurantRequirementsDTO;
import com.ftn.uns.ac.rs.theperfectmeal.model.Restaurant;
import com.ftn.uns.ac.rs.theperfectmeal.model.Cuisine;
import com.ftn.uns.ac.rs.theperfectmeal.model.MusicGenre;

import com.ftn.uns.ac.rs.theperfectmeal.model.Occassion;
import com.ftn.uns.ac.rs.theperfectmeal.model.Prices;
import com.ftn.uns.ac.rs.theperfectmeal.model.Distance;

rule "Wanted cuisine"
agenda-group "fill-restaurant-requirements"
salience 10
lock-on-active true
when
	$req: RestaurantRequirements($cuisine: cuisine)
then
	System.out.println("Cuisine type added - " + $cuisine);
	modify($req){setCuisine($cuisine);};

end;

rule "Wanted occassion"
agenda-group "fill-restaurant-requirements"
salience 10
lock-on-active true
when
	$req: RestaurantRequirements($occassion: occassion)

then
	System.out.println("Occassion type added - " + $occassion);
	modify($req){setOccassion($occassion);};

end;

rule "Wanted prices"
agenda-group "fill-restaurant-requirements"
salience 10
lock-on-active true
when
	$req: RestaurantRequirements($prices: prices)
then
	System.out.println("Prices added - " + $prices);
	modify($req){setPrices($prices);};

end;

rule "Pet friendy restaurant "
agenda-group "fill-restaurant-requirements"
salience 10
lock-on-active true
when
	$req: RestaurantRequirements(petFriendly==true)
then
	System.out.println("Pet-friendly added");
	modify($req){setPetFriendly(true);};

end;

rule "User's location "
agenda-group "fill-restaurant-requirements"
salience 10
lock-on-active true
when
	$req: RestaurantRequirements($lon: lon, $lat: lat, $lon != 0 && $lat != 0)
	
then
	System.out.println("User's location added - " + $lon + ", "+ $lat);
	modify($req){setLon($lon);};
	modify($req){setLat($lat);};
	modify($req){setDistance(Distance.NONE);};

end;

rule "Car park "
agenda-group "fill-restaurant-requirements"
salience 10
lock-on-active true
when
	$req: RestaurantRequirements($car: goingByCar, $car == true)
	 
then
	System.out.println("User is going by car - parking added.");
	modify($req){setHasCarPark(true);};

end;


rule "Access for disabled "
agenda-group "fill-restaurant-requirements"
salience 10
lock-on-active true
when
	$req: RestaurantRequirements(accessForDisabled == true)

then
	System.out.println("Access for disabled set true.");
	modify($req){setAccessForDisabled(true);};

end;

rule "Business meal "
agenda-group "fill-restaurant-requirements"
salience 5
lock-on-active true
when
	$req: RestaurantRequirements( $occassion: occassion, $occassion == Occassion.BUSINESS_MEAL )
then
	System.out.println("Business hall set true.");
	modify($req){setHasBusinessHall(true);};


end;

rule "Business meal 2 "
agenda-group "fill-restaurant-requirements"
salience 5
lock-on-active true
when
	$req: RestaurantRequirements( $occassion: occassion, $occassion == Occassion.BUSINESS_MEAL )
then
	System.out.println("Wifi set true.");
	modify($req){setHasWifi(true);};


end;
rule "Business meal 3"
agenda-group "fill-restaurant-requirements"
salience 5
lock-on-active true
when
	$req: RestaurantRequirements( $occassion: occassion, $occassion == Occassion.BUSINESS_MEAL )
then
	System.out.println("Live music set false.");
	modify($req){setLiveMusic(false);};

end;

rule "Family meal with kids "
agenda-group "fill-restaurant-requirements"
salience 5
lock-on-active true
when
	$req: RestaurantRequirements( $occassion: occassion, $occassion == Occassion.FAMILY_WITH_KIDS )
then
	System.out.println("Playground set true;");
	modify($req){setHasPlayground(true);};

end;

rule "Romantic date"
agenda-group "fill-restaurant-requirements"
salience 5
lock-on-active true
when
	$req: RestaurantRequirements( $occassion: occassion, $occassion == Occassion.ROMANTIC_DATE )
then
	System.out.println("Live music, serving alcohol and piano set true;");
	modify($req){setLiveMusic(true);};
	modify($req){setServingAlcohol(true);};
	modify($req){setMusicGenre(MusicGenre.PIANO);};

end;

rule "Celebration"
agenda-group "fill-restaurant-requirements"
salience 5
lock-on-active true
when
	$req: RestaurantRequirements( $occassion: occassion, $occassion == Occassion.CELEBRATION_DAY )
then
	System.out.println("Live music and alcohol set true;");
	modify($req){setLiveMusic(true);};
	modify($req){setServingAlcohol(true);};
	
	modify($req){setHasSmokingPart(true);};
	//modify($req){setServingAlcohol(true);};

end;



//rule "Celebration night"
//agenda-group "fill-restaurant-requirements"
//salience 5
//lock-on-active true
//when
	//$req: RestaurantRequirements( $occassion: occassion, $occassion == Occassion.CELEBRATION_NIGHT )
//then
	//System.out.println("Live music,pop, serving alcohol and smoking part set true");
	//modify($req){setLiveMusic(true);};
	//modify($req){setHasSmokingPart(true);};
	//modify($req){setServingAlcohol(true);};
	//modify($req){setMusicGenre(MusicGenre.TAMBOURINES);};
//end;

